[build]
publish = "dist"
command = "yarn build"

[build.environment]
NODE_VERSION = "18"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''